version: '2'

services:
  apache:
    image: geerlingguy/php-apache:latest
    container_name: travelBlog_apache
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html

volumes:
  composer-cache:
    driver: local
